# Generated by Django 4.0.2 on 2022-07-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_news_shortener_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='user',
        ),
    ]
